<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>80274561-1dc5-47db-a0f5-6ae21f2ed346</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />   
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fun.With.Dev.Palindromes.Contracts\Fun.With.Dev.Palindromes.Contracts.csproj" />
    <ProjectReference Include="..\Fun.With.Dev.Palindromes.Manager\Fun.With.Dev.Palindromes.Manager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="Properties\ServiceDependencies\FunWithDevPalindromes\" />
  </ItemGroup>

</Project>
